export default {
  id: 28,
  name: "jack o' lantern (lit)",
  description: "A bright pumpkin lantern burning with an everlasting flame. Symbol of Halloween night.",
  rarity: "rare",
  icon: "🎃",
  type: "material",
  value: 1800,
  sellvalue: 450,
  obtainable: false,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: true,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ["dependencies", "execute", "disassemble"],
};