export default {
  id: 18,
  name: "adamantite ore",
  description: "A near-indestructible ore.",
  rarity: "epic",
  icon: "",
  type: "material",
  value: 6500,
  sellvalue: 1625,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};