export default {
  id: 19,
  name: "enchanted wood",
  description: "Wood imbued with magic.",
  rarity: "epic",
  icon: "",
  type: "material",
  value: 5800,
  sellvalue: 1450,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};