export default {
  id: 25,
  name: "jack o' lantern",
  description: "A carved pumpkin glowing with eerie light. Its flame never seems to fade.",
  rarity: "epic",
  icon: "🎃",
  type: "material",
  value: 1200,
  sellvalue: 300,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: true,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ["dependencies", "execute", "disassemble"],
};
