export default {
  id: 17,
  name: "mithril ore",
  description: "A rare, lightweight silver-blue metal.",
  rarity: "epic",
  icon: "",
  type: "material",
  value: 6000,
  sellvalue: 1500,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};
