export default {
  id: 15,
  name: "diamond",
  description: "A flawless, sparkling diamond.",
  rarity: "legendary",
  icon: "💎",
  type: "material",
  value: 3000,
  sellvalue: 750,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 2,
  maxEnchantCount: 1,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  disassemble() {},
  dependencies: ``,
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};
