export default {
  id: 15,
  name: "bone",
  description: "A sturdy animal bone.",
  rarity: "common",
  icon: "🦴",
  type: "material",
  value: 100,
  sellvalue: 25,
  enchantable: false,
  obtainable: true,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};
