export default {
  id: 14,
  name: "feather",
  description: "Light as air, useful for arrows or charms.",
  rarity: "common",
  icon: "<:BCTfeather:1413745295908671538>",
  type: "material",
  value: 80,
  sellvalue: 20,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};