export default {
  id: 24,
  name: "melted wax",
  description: "Soft, warm wax from melted candles. Still carries a faint scent of mystery.",
  rarity: "uncommon",
  icon: "🕯️",
  type: "material",
  value: 380,
  sellvalue: 90,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: true,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ["dependencies", "execute", "disassemble"],
};
