export default {
  id: 12,
  name: "plank",
  description: "A wooden plank, useful for crafting.",
  rarity: "common",
  icon: "<:BCTwood_plank:1413742348634030132>",
  type: "material",
  value: 300,
  sellvalue: 75,
  obtainable: false,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};