export default {
  id: 10,
  name: "stick",
  description: "A simple wooden stick.",
  rarity: "common",
  icon: "<:BCTstick:1413743667910410342>",
  type: "material",
  value: 100,
  sellvalue: 25,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};
