export default {
  id: 9,
  name: "stone",
  description: "A stone.",
  rarity: "common",
  icon: "🪨",
  type: "material",
  value: 900,
  sellvalue: 300,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 1,
  maxEnchantCount: 3,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};