export default {
  id: 1,
  name: 'Unnamed Item',
  description: '',
  rarity: 'common',
  icon: '❔',
  type: 'misc',
  value: 0,
  sellvalue: 0,
  obtainable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  enchantable: false,
  sellable: false,
  stackable: false,
  maxstack: 1,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  disassemble() {},
  dependencies: ``,
  execute: (user, item, count, dep) => {},
  _emptyAllowed: ['dependencies'],
};
