export default {
  id: 1,
  name: "Salmon",
  rarity: "common",
  type: "fish",
  _mutation: undefined,
  get mutation() { return this._mutation ?? "undefined"; },
  dredcoinReward: [50, 100],
  expReward: [1, 2.5],
  value: 800,
  sellvalue: 200,
  shakeRange: [3, 7],
  resistance: 1.2,
  weightRange: [1.2, 4.5],
  lengthRange: [30, 75],
  rodLevelRequired: 1,
  enchantable: false,
  maxEnchantSlot: 3,
  maxEnchantCount: 3,
  obtainable: true,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: true,
  consumable: true,
  get shakeTime() { return 5000 * this.shakeRange[0] / this.shakeRange[1] },
  dependencies: ``,
  execute: async (user, fish, count, dep) => {},
  _emptyAllowed: ['dependencies', '_mutation'],
};