export default {
  id: 1,
  name: 'Unnamed Pet',
  description: '',
  rarity: 'common',
  type: 'default',
  value: 100,
  sellable: false,
  tradeable: false,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  obtainable: false,
  lv: 1,
  maxLv: 10,
  hungry: 100,
  dependencies: ``,
  feed: (user, pet, item, count, dep) => {},
  apply: (user, pet, dep) => {},
  _emptyAllowed: ['dependencies', 'feed', 'apply'],
};
