export default {
  id: 29,
  name: "pumpkin core",
  description: "The dense, glowing heart of a ripe pumpkin. Warm to the touch.",
  rarity: "uncommon",
  icon: "🎃",
  type: "material",
  value: 650,
  sellvalue: 150,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: true,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ["dependencies", "execute", "disassemble"],
};
