export default {
  id: 22,
  name: "slime",
  description: "A green ball.",
  rarity: "uncommon",
  icon: "",
  type: "material",
  value: 450,
  sellvalue: 110,
  obtainable: true,
  enchantable: false,
  maxEnchantSlot: 0,
  maxEnchantCount: 0,
  sellable: true,
  stackable: true,
  maxstack: Number.MAX_SAFE_INTEGER,
  tradeable: false,
  consumable: false,
  disassemblable: false,
  dependencies: ``,
  disassemble() {},
  async execute(user, item, dep, count = 1) {},
  _emptyAllowed: ['dependencies', 'execute', 'disassemble'],
};